Projeto 6
EricaSantos2109/TODO-list pull request #6
Opened 2023-02-13 13:48 UTC by EricaSantos2109

2023-02-15 20:02 UTC, wrongbyte requested changes

2023-02-15 20:02 UTC, wrongbyte commented on src/cli.rs
> +impl TodoCli {
Faltou formatar esse arquivo. `cargo fmt`

2023-02-15 20:02 UTC, wrongbyte commented on src/terminal.rs
> +    fn run(&mut self, todos: &mut dyn TodoStorage) -> Result<(), TerminalError> {
O `todos`que seria passado como argumento da função não é utilizado; em vez disso você está criando um `Todos`na linha 60. Você poderia criar o `Todos` na main e passar como argumento quando chamasse `run()` por lá.

2023-02-15 20:02 UTC, wrongbyte commented on src/terminal.rs
> +    fn user_option(&mut self, option: UserOption, todos: &mut Todos) -> Result<(), TerminalError> {
Eu acho que essa função não é necessária.. Esse `match` poderia ser feito já na função `run()`, usando por exemplo `match self.select_user_command()?` . WDYT?

2023-02-15 20:02 UTC, wrongbyte commented on src/todos.rs
> +        return &self.list;
Os `return` dessa linha e da linha 26 não são necessários

2023-02-15 20:02 UTC, wrongbyte commented on src/todos.rs
> -            list: Vec::with_capacity(15),
Por que usar `with_capacity`? :thinking:

2023-02-16 17:22 UTC, luisholanda commented on src/todos.rs
> -            list: Vec::with_capacity(15),
Seria para poupar realocações a medida que novos elementos fossem adicionados, mas acho overkill nesse projeto.

2023-02-16 17:24 UTC, luisholanda commented on src/terminal.rs
> +    fn show_todos(&mut self, todos: &mut dyn TodoStorage) -> Result<(), TerminalError>;
Acho estranho esse método receber um `&mut _` para os todos, por que precisariamos modificar os todos enquanto os listamos? Mesma coisa no `show_list`.

2023-02-20 12:50 UTC, luisholanda approved these changes

2023-02-20 18:25 UTC, wrongbyte approved these changes

2023-02-20 18:25 UTC, wrongbyte commented on src/cli.rs
> +        if let Err(error) = self.user_interface.run(self.todo_storage.as_mut()) {
Não acho que faça muito sentido ter dois métodos `run()`. A responsabilidade de "rodar" a aplicação deveria ficar exclusivamente com a struct `TodoCli`, e ela que deveria "fazer uso" dos parâmetros `user_interface` e `todo_storage`.

2023-02-20 18:25 UTC, wrongbyte commented on src/terminal.rs
>              style("Bem vindo ao TODO List").yellow().bold(),
Esse `writeln!` que mostra a mensagem de boas-vindas poderia se tornar um método de `UserInterface`, o que acha?

2023-02-20 18:27 UTC, merged